queue_rules:
  - name: default
    conditions:
      # Conditions to get out of the queue (= merged)
      - check-success=Build CD

pull_request_rules:
  - name: Automatically merge base service updates
    conditions:
      - label=baseServiceUpdate
      - files=gradle.properties
      - "#files=1"
    actions:
      queue:
        method: merge
        strict: default
      label:
        add: ["auto merged"]