name: Auto approve base service update

on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    name: Auto approve base service update
    if: ${{ github.event.label.name == 'baseServiceUpdate' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check PR label
        uses: NathanielHill/check-pr-label-action@v4.0.0
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          valid-labels: 'baseServiceUpdate'
