name: Build CD Images

on:
  push:
    branches:
      - main
      - "release-[0-9]+.[0-9]+.x"

jobs:
  publish_images:
    env:
      ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
      ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Fetch full history
        run: git fetch --prune --tags --unshallow

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v1

      - name: Generate Variables
        id: variables
        uses: armory-io/astrolabe-build-defaults@main
        with:
          red_hat_pid: ${{ secrets.REDHAT_PID }}

      - name: Build Image
        run: |
          ./gradlew docker \
            -PcdBuild=true \
            -PimageName=${{ steps.variables.outputs.artifactory_image_name }} \
            -Pversion=${{ steps.variables.outputs.version }} \
            -Partifactory_user=${ARTIFACTORY_USER} \
            -Partifactory_password=${ARTIFACTORY_PASSWORD}
      - name: Publish Image To Artifactory
        run: |
          jfrog rt config artifactory --interactive=false \
            --url ${{ steps.variables.outputs.artifactory_url }} \
            --user ${ARTIFACTORY_USER} \
            --password ${ARTIFACTORY_PASSWORD}
          jfrog rt dp ${{ steps.variables.outputs.artifactory_image_name }} ${{ steps.variables.outputs.artifactory_docker_repository }} \
            --build-name=${{ steps.variables.outputs.build_name }} \
            --build-number=${{ steps.variables.outputs.build_number }}
          jfrog rt bag ${{ steps.variables.outputs.build_name }} ${{ steps.variables.outputs.build_number }}
          jfrog rt bp ${{ steps.variables.outputs.build_name }} ${{ steps.variables.outputs.build_number }} \
            --build-url=${{ steps.variables.outputs.build_url }}
